# Generated by Django 3.1.3 on 2020-12-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0002_python_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python.python', verbose_name='강의제목'),
        ),
    ]
