# Generated by Django 3.1.4 on 2020-12-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaedalMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('student_id', models.IntegerField(verbose_name='학번')),
                ('phone_number', models.IntegerField(blank=True, default=0, verbose_name='전화번호')),
                ('haetoos_id', models.CharField(blank=True, max_length=50, verbose_name='ID')),
                ('haetoos_ps', models.CharField(blank=True, max_length=50, verbose_name='비밀번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
        ),
    ]
