# Generated by Django 3.1.4 on 2020-12-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haetoos_id', models.CharField(max_length=64, verbose_name='아이디')),
                ('haetoos_pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('student_id', models.IntegerField(verbose_name='학번')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('phone_number', models.IntegerField(blank=True, default=0, verbose_name='전화번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '해투스 사용자',
                'verbose_name_plural': '해투스 사용자',
                'db_table': 'haetoos_user',
            },
        ),
        migrations.DeleteModel(
            name='HaedalMember',
        ),
    ]
