# Generated by Django 3.1.4 on 2020-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201218_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='haetoos_pw',
            new_name='haetoos_ps',
        ),
        migrations.AlterField(
            model_name='user',
            name='haetoos_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='아이디'),
        ),
    ]
