# Generated by Django 3.1.3 on 2020-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_name', models.CharField(max_length=512, verbose_name='강의이름')),
                ('lec_main', models.TextField(verbose_name='강의내용')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': 'Web 강의',
                'verbose_name_plural': 'Web 강의',
                'db_table': 'web_list',
            },
        ),
    ]
