# Generated by Django 3.1.3 on 2020-12-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('user', models.CharField(max_length=64, verbose_name='이름')),
                ('anony', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=8, verbose_name='익명')),
                ('dat', models.IntegerField(default=0)),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.web', verbose_name='강의제목')),
            ],
        ),
    ]
