# Generated by Django 3.1.3 on 2020-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haetoos_id', models.CharField(max_length=64, verbose_name='아이디')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('studentId', models.IntegerField(verbose_name='학번')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '해투스 사용자',
                'verbose_name_plural': '해투스 사용자',
                'db_table': 'haetoos_user',
            },
        ),
    ]
